from app.agents.base import BaseAgent
from app.config.logging import logger
from app.services.github_service import create_github_service
from app.services.repo_service import RepoService
import subprocess
import asyncio
from pathlib import Path


class GitHubAgent(BaseAgent):
    name = "github_agent"

    async def execute(self, task_context: Dict[str, Any]) -> Dict[str, Any]:
        await self.log("Starting GitHub operations", level="info")

        action = task_context.get("action", "create_pr")
        user = task_context.get("user", {})
        repository = task_context.get("repository", {})
        changes = task_context.get("changes", [])
        task = task_context.get("task", {})

        access_token = user.get("github_access_token")
        if not access_token:
            return {"status": "failed", "error": "No GitHub access token"}

        github = create_github_service(access_token)
        repo_service = RepoService(access_token)

        result = {"status": "success"}

        try:
            if action == "create_pr":
                owner, repo_name = repository["full_name"].split("/")
                branch_name = f"coding-assistant/{task.get('id', 'task')[:8]}"

                default_branch = await github.get_default_branch(owner, repo_name)
                branch_sha = await github.get_branch_ref(owner, repo_name, default_branch)
                await github.create_branch(owner, repo_name, branch_name, branch_sha["object"]["sha"])

                for change in changes:
                    await github.create_or_update_file(
                        owner=owner,
                        repo=repo_name,
                        path=change.get("file", "generated.py"),
                        content=change.get("content", ""),
                        message=f"AI: {change.get('description', 'Generated code')}",
                        branch=branch_name
                    )

                pr = await github.create_pull_request(
                    owner=owner,
                    repo=repo_name,
                    title=task.get("title", "AI-generated changes"),
                    body=task.get("description", "") + "\n\nGenerated by Coding Assistant Agent",
                    head=branch_name,
                    base=default_branch
                )

                result["pr_number"] = pr.get("number")
                result["pr_url"] = pr.get("html_url")
                result["branch"] = branch_name

                await self.log(f"Created PR #{pr.get('number')}", level="info")

        except Exception as e:
            await self.log(f"GitHub operation failed: {e}", level="error")
            return {"status": "failed", "error": str(e)}

        return result
